djtest/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('test1.urls')),
    path('admin/', admin.site.urls),
]

test1/urls.py
from django.conf.urls import url
from test1 import views

app_name = 'test1'

urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^loginVerify/$', views.loginVerify, name='loginVerify'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^index/$', views.index, name='index'),
    url(r'^detail/(?P<task_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^detail_p/$', views.detail_p, name='detail_p'),
    url(r'^crontab_schedule/$', views.crontab_schedule, name='crontab_schedule'),
    url(r'^rabbitmq/$', views.rabbitmq, name='rabbitmq'),
    url(r'^rabbitmq_sync/$', views.rabbitmq_sync, name='rabbitmq_sync'),
    url(r'^rabbitmq_add/$', views.rabbitmq_add, name='rabbitmq_add'),
    url(r'^rabbitmq_add_ex_qu_rk/$', views.add_ex_qu_rk, name='rabbitmq_add_ex_qu_rk'),
    url(r'^rabbitmq_queue_monitor/$', views.queue_monitor, name='rabbitmq_queue_monitor'),
    url(r'^get_tasks/$', views.get_registry_task, name='get_tasks'),
    url(r'^get_exchanges/$', views.get_exchanges, name='get_exchanges'),
    url(r'^get_exchanges_table/$', views.get_exchanges_table, name='get_exchanges_table'),
    url(r'^get_queues/$', views.get_queues, name='get_queues'),
    url(r'^get_queues_table/$', views.get_queues_table, name='get_queues_table'),
    url(r'^get_routing_key_with_eqid/$', views.get_routing_key_eqid, name='get_routing_key_with_eqid'),
    url(r'^add_interval_every_period/$', views.add_interval_every_period, name='add_interval_every_period'),
    url(r'^interval_schedule/$', views.interval_schedule, name='interval_schedule'),
    url(r'^addtask/$', views.addtask, name='addtask'),
    url(r'^add_test$', views.add_test, name='add_test'),
    url(r'^add/$', views.add1, name='add1'),
    url(r'^result$', views.result, name='result'),
    url(r'^add_delay$', views.add_delay, name='add_delay'),
    url(r'^add_timeout$', views.add_timeout, name='add_timeout'),
    url(r'^db_exec$', views.db_exec, name='db_exec'),
    url(r'^add_task$', views.add_task, name='add_task'),
    url(r'^update_task$', views.update_task, name='update_task'),
    url(r'^get_tasks_list', views.get_tasks_list, name='get_tasks_list'),
    url(r'^get_running_tasks_table', views.get_running_tasks_table, name='get_running_tasks_table'),
    url(r'^add_interval$', views.add_interval, name='add_interval'),
    url(r'^get_interval_list$', views.get_interval, name='get_interval_list'),
    url(r'^get_interval_list_p$', views.get_interval_list_p, name='get_interval_list_p'),
    url(r'^get_interval_list_sep$', views.get_interval_list_sep, name='get_interval_list_sep'),
    url(r'^delete_interval$', views.delete_interval, name='delete_interval'),
    url(r'^update_interval$', views.update_interval, name='update_interval'),
    url(r'^get_crontab_list_sep$', views.get_crontab_list_sep, name='get_crontab_list_sep'),
    url(r'^update_crontab$', views.update_crontab, name='update_crontab'),
    url(r'^add_crontab$', views.add_crontab_all, name='add_crontab'),
    url(r'^delete_crontab$', views.delete_crontab, name='delete_crontab'),
    url(r'^display_new_tasks$', views.display_new_tasks, name='display_new_tasks'),
    url(r'^get_tasks_status', views.get_tasks_status_p, name='get_tasks_status'),
    url(r'^chart_bar', views.chart_bar, name='chart_bar'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}主页{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="/static/bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="/static/dist/css/skins/_all-skins.min.css">
  <!-- Morris chart -->
  <link rel="stylesheet" href="/static/bower_components/morris.js/morris.css">
  <!-- jvectormap -->
  <link rel="stylesheet" href="/static/bower_components/jvectormap/jquery-jvectormap.css">
  <!-- Date Picker -->
  <link rel="stylesheet" href="/static/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="/static/bower_components/bootstrap-daterangepicker/daterangepicker.css">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="/static/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

    <link rel="stylesheet" href="/static/plugins/bootstrap3-editable/css/bootstrap-editable.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/plugins/bootstrap-table/bootstrap-table.min.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

{% block css %}{% endblock %}

</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>T</b>PM</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>计划任务</b>管理平台</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
{#          <li class="dropdown messages-menu">#}
{#            <a href="#" class="dropdown-toggle" data-toggle="dropdown">#}
{#              <i class="fa fa-envelope-o"></i>#}
{#              <span class="label label-success">4</span>#}
{#            </a>#}
{#            <ul class="dropdown-menu">#}
{#              <li class="header">此功能暂缺</li>#}
{##}
{#                  <!-- end message -->#}
{##}
{#            </ul>#}
{#          </li>#}
{#          <!-- Notifications: style can be found in dropdown.less -->#}
{#          <li class="dropdown notifications-menu">#}
{#            <a href="#" class="dropdown-toggle" data-toggle="dropdown">#}
{#              <i class="fa fa-bell-o"></i>#}
{#              <span class="label label-warning">10</span>#}
{#            </a>#}
{#            <ul class="dropdown-menu">#}
{#              <li class="header">此功能暂缺</li>#}
{##}
{#            </ul>#}
{#          </li>#}
{#          <!-- Tasks: style can be found in dropdown.less -->#}
{#          <li class="dropdown tasks-menu">#}
{#            <a href="#" class="dropdown-toggle" data-toggle="dropdown">#}
{#              <i class="fa fa-flag-o"></i>#}
{#              <span class="label label-danger">9</span>#}
{#            </a>#}
{#            <ul class="dropdown-menu">#}
{#              <li class="header">此功能暂缺</li>#}
{##}
{#            </ul>#}
{#          </li>#}
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="/static/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
              <span class="hidden-xs">管理员</span>
            </a>
          </li>
          <!-- Control Sidebar Toggle Button -->

        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="/static/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Ooops</p>
{#          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>#}
        </div>
      </div>
      <!-- search form -->
{#      <form action="#" method="get" class="sidebar-form">#}
{#        <div class="input-group">#}
{#          <input type="text" name="q" class="form-control" placeholder="Search...">#}
{#          <span class="input-group-btn">#}
{#                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>#}
{#                </button>#}
{#              </span>#}
{#        </div>#}
{#      </form>#}
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">导航栏</li>
        <li class="active treeview">
          <a href="{% url 'test1:dashboard' %}">
            <i class="fa fa-dashboard"></i> <span>仪表盘</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
            <ul class="treeview-menu">
                <li><a href="{% url 'test1:dashboard' %}"><i class="fa fa-circle-o"></i>仪表盘</a></li>

            </ul>

        </li>
        <li class="treeview">
          <a href="{% url 'test1:index' %}">
            <i class="fa fa-table"></i><span>任务管理</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
            <ul class="treeview-menu">
                <li><a href="{% url 'test1:index' %}"><i class="fa fa-circle-o"></i>任务列表</a></li>
                <li><a href="{% url 'test1:addtask' %}"><i class="fa fa-circle-o"></i>新增任务</a></li>

            </ul>
        </li>

        <li class="treeview">
          <a href="">
            <i class="fa fa-clock-o"></i>
            <span>时间计划</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url 'test1:crontab_schedule' %}"><i class="fa fa-circle-o"></i>定时计划</a></li>
            <li><a href="{% url 'test1:interval_schedule' %}"><i class="fa fa-circle-o"></i>间隔计划</a></li>

          </ul>
        </li>

          <li class="treeview">
          <a href="">
            <i class="fa fa-calendar-minus-o"></i>
            <span>RabbitMQ管理</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url 'test1:rabbitmq' %}"><i class="fa fa-circle-o"></i>同步列表</a></li>
              <li><a href="{% url 'test1:rabbitmq_add' %}"><i class="fa fa-circle-o"></i>新增</a></li>
{#            <li><a href="{% url 'test1:interval_schedule' %}"><i class="fa fa-circle-o"></i></a></li>#}

          </ul>
        </li>


      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
   {% block content %}{% endblock %}
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 0.7.0
    </div>
    <strong>Copyright &copy; 2018 <a href="#">JailGe Studio</a>.</strong> All rights
    reserved.
  </footer>


</div>
<!-- ./wrapper -->

<!-- jQuery 3 -->
<script src="/static/bower_components/jquery/dist/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="/static/bower_components/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Morris.js charts -->
<script src="/static/bower_components/raphael/raphael.min.js"></script>
<script src="/static/bower_components/morris.js/morris.min.js"></script>
<!-- Sparkline -->
<script src="/static/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- jvectormap -->
<script src="/static/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="/static/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- jQuery Knob Chart -->
<script src="/static/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="/static/bower_components/moment/min/moment.min.js"></script>
<script src="/static/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- datepicker -->
<script src="/static/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="/static/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<!-- Slimscroll -->
<script src="/static/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="/static/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/static/dist/js/adminlte.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="/static/dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/static/dist/js/demo.js"></script>
<script src="/static/js/jquery-3.3.1.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/plugins/bootstrap3-editable/js/bootstrap-editable.js"></script>
<script src="/static/plugins/bootstrap-table/bootstrap-table.js"></script>
<script src="/static/plugins/bootstrap-table/locale/bootstrap-table-zh-CN.js"></script>
<script src="/static/plugins/bootstrap-table/extensions/editable/bootstrap-table-editable.js"></script>

<script>
    $(function () {
   $.ajaxSetup({
       headers:{"X-CSRFToken":getCookie("csrftoken")}
   });
});

function getCookie(name) {
    var arr,reg=new RegExp("(^|)"+name+"=([^;]*)(;|$)");
    if(arr=document.cookie.match(reg)){
        return unescape(arr[2]);
    }else{
        return null;
    }
}
</script>

{% block script %}{% endblock %}

</body>
</html>