djtest/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('test1.urls')),
    path('admin/', admin.site.urls),
]

test1/urls.py
from django.conf.urls import url
from test1 import views

app_name = 'test1'

urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^loginVerify/$', views.loginVerify, name='loginVerify'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^index/$', views.index, name='index'),
    url(r'^detail/(?P<task_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^detail_p/$', views.detail_p, name='detail_p'),
    url(r'^crontab_schedule/$', views.crontab_schedule, name='crontab_schedule'),
    url(r'^rabbitmq/$', views.rabbitmq, name='rabbitmq'),
    url(r'^rabbitmq_sync/$', views.rabbitmq_sync, name='rabbitmq_sync'),
    url(r'^rabbitmq_add/$', views.rabbitmq_add, name='rabbitmq_add'),
    url(r'^rabbitmq_add_ex_qu_rk/$', views.add_ex_qu_rk, name='rabbitmq_add_ex_qu_rk'),
    url(r'^rabbitmq_queue_monitor/$', views.queue_monitor, name='rabbitmq_queue_monitor'),
    url(r'^get_tasks/$', views.get_registry_task, name='get_tasks'),
    url(r'^get_exchanges/$', views.get_exchanges, name='get_exchanges'),
    url(r'^get_exchanges_table/$', views.get_exchanges_table, name='get_exchanges_table'),
    url(r'^get_queues/$', views.get_queues, name='get_queues'),
    url(r'^get_queues_table/$', views.get_queues_table, name='get_queues_table'),
    url(r'^get_routing_key_with_eqid/$', views.get_routing_key_eqid, name='get_routing_key_with_eqid'),
    url(r'^add_interval_every_period/$', views.add_interval_every_period, name='add_interval_every_period'),
    url(r'^interval_schedule/$', views.interval_schedule, name='interval_schedule'),
    url(r'^addtask/$', views.addtask, name='addtask'),
    url(r'^add_test$', views.add_test, name='add_test'),
    url(r'^add/$', views.add1, name='add1'),
    url(r'^result$', views.result, name='result'),
    url(r'^add_delay$', views.add_delay, name='add_delay'),
    url(r'^add_timeout$', views.add_timeout, name='add_timeout'),
    url(r'^db_exec$', views.db_exec, name='db_exec'),
    url(r'^add_task$', views.add_task, name='add_task'),
    url(r'^update_task$', views.update_task, name='update_task'),
    url(r'^get_tasks_list', views.get_tasks_list, name='get_tasks_list'),
    url(r'^get_running_tasks_table', views.get_running_tasks_table, name='get_running_tasks_table'),
    url(r'^add_interval$', views.add_interval, name='add_interval'),
    url(r'^get_interval_list$', views.get_interval, name='get_interval_list'),
    url(r'^get_interval_list_p$', views.get_interval_list_p, name='get_interval_list_p'),
    url(r'^get_interval_list_sep$', views.get_interval_list_sep, name='get_interval_list_sep'),
    url(r'^delete_interval$', views.delete_interval, name='delete_interval'),
    url(r'^update_interval$', views.update_interval, name='update_interval'),
    url(r'^get_crontab_list_sep$', views.get_crontab_list_sep, name='get_crontab_list_sep'),
    url(r'^update_crontab$', views.update_crontab, name='update_crontab'),
    url(r'^add_crontab$', views.add_crontab_all, name='add_crontab'),
    url(r'^delete_crontab$', views.delete_crontab, name='delete_crontab'),
    url(r'^display_new_tasks$', views.display_new_tasks, name='display_new_tasks'),
    url(r'^get_tasks_status', views.get_tasks_status_p, name='get_tasks_status'),
    url(r'^chart_bar', views.chart_bar, name='chart_bar'),
]

test1/models.py
from django.db import models

# Create your models here.

class Exchanges(models.Model):
    name = models.CharField('名称', max_length=255, unique=True)

    def __str__(self):
        return 'Exchange:{}'.format(self.name)

class Queues(models.Model):
    name = models.CharField('名称', max_length=255, unique=True)

    def __str__(self):
        return 'Queue:{}'.format(self.name)

class Routing_keys(models.Model):
    name = models.CharField('名称', max_length=255, unique=True)
    exchange = models.ForeignKey(Exchanges, on_delete=models.CASCADE, null=True)
    queue = models.ForeignKey(Queues, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return 'Routing_key:{}'.format(self.name)


class superuser(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    create_date = models.DateTimeField('date published')

    def __str__(self):
        return 'username:{}'.format(self.username)




class Add(models.Model):
    task_id = models.CharField('任务ID', max_length=128)
    first = models.IntegerField('第一个值')
    second = models.IntegerField('第二个值')
    log_date = models.DateTimeField('创建时间')

    def __str__(self):
        return '{0}--{1}--{2}'.format(self.task_id, self.first, self.second)

    class Meta:
        verbose_name = '相加'
        verbose_name_plural = '相加'

test1/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from djcelery import models as celery_models
from djcelery import loaders
from celery.exceptions import SoftTimeLimitExceeded
from test1 import tasks
from test1.models import Add
from django.utils import timezone
from test1.models import Exchanges, Queues
from tools.handler import get_all_tasks_info, add_task_to_db, add_interval_to_db, get_interval_list, get_tasks_status, get_task_detail, get_interval_list_sep_all, update_interval_data, delete_interval_data
from tools.handler import get_crontab_list_sep_all, update_crontab_data, add_crontab_to_db, delete_crontab_data, update_task_with_id
from tools.handler import rbt_sync_routingkey, rbt_sync_exchanges, rbt_sync_queues, get_exchanges_db, get_queues_db, get_running_tasks, get_routing_key_with_eq_id
from tools.handler import get_all_tasks
from tools.supervisorctl import restart_beat
from celery import signature, chain, chord, group
from tools.msodbc import Odbc_Ms
from rbmapi import rbm_manage
from tools.ms import chain_task, group_task, ms_exec_test
from celery import registry
from .form import AddForm, SysConfigForm, IntervalForm
from test1.models import Exchanges, Queues, superuser
import re
import json




# Create your views here.

def dashboard(request):
    return render(request, 'test1/dashboard.html')

def chart_bar(request):
    if request.method == 'POST':
        tasks = list(celery_models.PeriodicTask.objects.all().values())
        return JsonResponse({'tasks_num':tasks})


def index(request):
    if request.method == 'POST':
        form = AddForm(request.POST, initial={'IntervalList':'seconds'})
        if form.is_valid():
            a = form.cleaned_data['a']
            b = form.cleaned_data['b']
            return HttpResponse(str(int(a) + int(b)))
    else:
        form = AddForm()

    return render(request, 'test1/index.html', {'form':form})
    # return render(request, 'test1/index.html')

def detail(request, task_id):
    task = get_object_or_404(celery_models.PeriodicTask, id=task_id)
    interval = celery_models.IntervalSchedule.objects.filter(id=task.interval_id).values()
    exchanges = Exchanges.objects.filter(name=task.exchange).values()
    queues = Queues.objects.filter(name=task.queue).values()
    td = task_id
    t = get_task_detail(task_id)

    task_dict = {
        'name': task.name,
        'task': task.task,
        'kwargs': task.kwargs,
        'queue': task.queue,
        'exchange': task.exchange,
        'routing_key': task.routing_key,
        'enabled': task.enabled,
        'interval_id': task.interval_id
    }
    return render(request, 'test1/detail.html', locals())


def detail_p(request):
    print(request.POST)
    if request == 'POST':
        task_id = request.POST.get('task_id')
        t = get_task_detail(task_id)
        return JsonResponse({'detail': t})

def crontab_schedule(request):
    return render(request, 'test1/crontabschedule.html')

def interval_schedule(request):
    return render(request, 'test1/intervalschedule.html')

# @login_required(redirect_field_name='',login_url='/')
def rabbitmq(request):
    queues = rbm_manage.rbt_get_all_queues()
    return render(request, 'test1/rabbitmq.html', {'queues':queues})

def rabbitmq_sync(request):
    if request.method == 'POST':
        e = []
        q = []
        exchanges_list = rbm_manage.rbt_get_all_exchanges()
        queues_list = rbm_manage.rbt_get_all_queues()
        for el in exchanges_list:
            r = rbt_sync_exchanges(el)
            if r is not False:
                e.append(r)
        for ql in queues_list:
            s = rbt_sync_queues(ql)
            if s is not False:
                q.append(s)
        return  JsonResponse({'ex_num':e.__len__(), 'qu_num':q.__len__()})


#获取 tasks的列表
def get_registry_task(request):
    task_list_all = get_all_tasks()
    return JsonResponse({'task_list': task_list_all})


def get_exchanges(request):
    exlist = get_exchanges_db()
    if request.method == 'POST':
        return JsonResponse({'exchanges_list':exlist})
    else:
        return JsonResponse({'data':exlist, 'totals':exlist.__len__()})

def get_exchanges_table(request):
    num = get_exchanges_db()
    if request.method == 'POST':
        cp = int(request.POST.get('cPage'))
        ps = int(request.POST.get('pSize'))
        exlist = get_exchanges_db(cp=cp, ps=ps)
        return JsonResponse({'data':exlist, 'totals':num.__len__()})


def get_queues(request):
    qlist = get_queues_db()
    if request.method == 'POST':
        return JsonResponse({'queues_list':qlist})
    else:
        return JsonResponse({'data':qlist, 'totals':qlist.__len__()})

#queues 分页查询
def get_queues_table(request):
    num = get_queues_db()
    if request.method == 'POST':
        cp = int(request.POST.get('cPage'))
        ps = int(request.POST.get('pSize'))
        qlist = get_queues_db(cp=cp, ps=ps)
        return JsonResponse({'data':qlist, 'totals':num.__len__()})

def get_routing_key_eqid(request):
    if request.method == 'POST':
        eid = request.POST.get('exchange')
        qid = request.POST.get('queue')
        rk = get_routing_key_with_eq_id(eid=eid,qid=qid)
        return JsonResponse({'routing_key':rk})

def rabbitmq_add(request):
    return render(request, 'test1/addrbt.html')

def add_ex_qu_rk(request):
    if request.method == 'POST':
        exchange = request.POST.get('exchange')
        queue = request.POST.get('queue')
        routing_key = request.POST.get('routing_key')
        res_ex = rbm_manage.rbt_put_exchange(ex=exchange,type='direct',durable='true')
        res_qu = rbm_manage.rbt_put_queue(qu=queue,durable='true')
        res_rk = rbm_manage.rbt_post_binding(ex=exchange,qu=queue,routing_key=routing_key)
        if res_ex and res_qu and res_rk:
            res_ex_db = rbt_sync_exchanges(exchange)
            res_qu_db = rbt_sync_queues(queue)
        # ex_id = get_object_or_404(Exchanges, name)
            if res_ex_db and res_qu_db:
                ex_id = list(Exchanges.objects.filter(name=exchange).values('id'))[0]['id']
                qu_id = list(Queues.objects.filter(name=queue).values('id'))[0]['id']
                rk = rbt_sync_routingkey(name=routing_key,eid=ex_id,qid=qu_id)
                if rk:
                    status = 'true'
                else:
                    status = 'false'
            else:
                status = 'false'
        else:
            status = 'false'
        # if res_ex and res_qu and res_rk and res_ex_db and res_qu_db:
        #     status = 'true'
        # else:
        #     status = 'false'
        return JsonResponse({'status':status})

#rbt_queue 实时图
def queue_monitor(request):
    if request.method == 'POST':
        all_messages = rbm_manage.rbt_get_all_queues_messages()
        queues = [q for q in all_messages]
        messages = [all_messages[m]['messages'] for m in all_messages]
        unacked = [all_messages[m]['unacked'] for m in all_messages]
        ready = [all_messages[m]['ready'] for m in all_messages]
        return JsonResponse({'queues':queues,'messages':messages,'unacked':unacked,'ready':ready})



def add_interval_every_period(request):
    if request.method == 'POST':
        every = int(request.POST.get('every'))
        period = request.POST.get('period')
        res = add_interval_to_db(every, period)
        # print(res)
        if res:
            status = 'true'
        else:
            status = 'false'
        return JsonResponse({'status': status})


def addtask(request):
    return render(request, 'test1/addtask.html')

def add_test(request):
    a = int(request.GET.get('a'))
    b = int(request.GET.get('b'))
    return HttpResponse(str(a + b))

# def index_form(request):
#     if request.method == 'POST':
#         form = AddForm(request.POST)
#         if form.is_valid():
#             a = form.cleaned_data['a']
#             b = form.cleaned_data['b']
#             return HttpResponse(str(int(a) + int(b)))
#         else:
#             form = AddForm()
#         return render(request, 'test1/index.html', {'form':form})

def add1(request):
    first = int(request.GET.get('first'))
    second = int(request.GET.get('second'))
    # result = chain(tasks.add.s(first, second), tasks.add.s(1), tasks.add.s(1))()
    # result = tasks.add.delay(first, second)
    result = chain_task(tasks.add, first, second, 1, 1)
    print(result)
    Add.objects.create(task_id=result.id, first=first, second=second, log_date=timezone.now())
    return render(request, 'test1/index.html')


def add_delay(request):
    first = int(request.GET.get('first_d'))
    second = int(request.GET.get('second_d'))
    result = tasks.add_delay.delay(first, second)
    print(result)
    Add.objects.create(task_id=result.id, first=first, second=second, log_date=timezone.now())
    return render(request, 'test1/index.html')

def add_timeout(request):
    first = int(request.GET.get('first_t'))
    second = int(request.GET.get('second_t'))
    try:
        result1 = tasks.add_timeout.delay(first, second)
    except SoftTimeLimitExceeded:
        result1.revoke()
    print(result1,result1.status)
    Add.objects.create(task_id=result1.id, first=first, second=second, log_date=timezone.now())
    return render(request, 'test1/index.html')

def result(request):
    res = get_all_tasks_info()
    return render(request, 'test1/result.html', {'result': res})

def db_exec(request):
    sql = request.GET.get('sql')
    para = request.GET.get('para')
    sqlist = [sql,]
    print(sqlist)
    res = tasks.db_exec.delay(sqlist)
    print(res)
    Add.objects.create(task_id=res.id, log_date=timezone.now())
    return render(request, 'test1/index.html')



def add_task(request):
    if request.method == 'POST':
        task_name = request.POST.get('task_name')
        task = request.POST.get('task')

test1/templates/test1/addrbt.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block css %}
<link rel="stylesheet" href="/static/plugins/bootstrap3-editable/css/bootstrap-editable.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/plugins/bootstrap-table/bootstrap-table.min.css">


{% endblock %}

{% block content %}

    <section class="content-header">
    <h1>
        RabbitMQ
        <small>新增 Exchanges & Queues</small>
    </h1>

    <ol class="breadcrumb">
        <li><a href="{% url 'test1:index' %}"><i class="fa fa-dashboard"></i>主页 </a> </li>
        <li class="active">新增 Exchanges & Queues</li>
    </ol>
    </section>

<br>
    <br>
    exchange:<input type="text" id="exchange" name="exchange" value="">
    queue:<input type="text" id="queue" name="queue" value="">
    routing_key:<input type="text" id="routing_key" name="routing_key" value="">
    <button type="button" id="add">新增</button><br>
    <label id="result_label" ></label>

    <br>
    <div id="main" style="width: 100%; height:400px"></div>



{% endblock %}

{% block script %}
        <script src="/static/js/csrf.js"></script>
    <script src='/static/js/jquery-3.3.1.min.js'></script>
<script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/echarts.common.min.js"></script>

    <script>

    $("#add").click(function () {
        post_data = {
            'exchange':$('#exchange').val(),
            'queue':$('#queue').val(),
            'routing_key':$('#routing_key').val()
        };
        $.post("{% url 'test1:rabbitmq_add_ex_qu_rk' %}", post_data, function(data){
            if(data['status'] == 'true'){
                clean_and_focus();
                $("#result_label").html("保存成功");
            }else {
                clean_and_focus();
                $("#result_label").html("保存失败");
            }
        });
    });


    /*
* 清空页面并获取焦点
 */
     function clean_and_focus() {
         $("#task_name").val("").focus();
         $("#task").val("");
         $("#kwargs").val("");
         $("#exchange").val("0");
         $("#queue").val("0");
         $("#routing_key").val("");
         $("#interval_list").val("0");
     }




    /*
允许运行 ajax
 */
$(function () {
   $.ajaxSetup({
       headers:{"X-CSRFToken":getCookie("csrftoken")}
   });
});

function getCookie(name) {
    var arr,reg=new RegExp("(^|)"+name+"=([^;]*)(;|$)");
    if(arr=document.cookie.match(reg)){
        return unescape(arr[2]);
    }else{
        return null;
    }
}

    </script>
    
    <script>
        $(function () {
            var myChart = echarts.init(document.getElementById('main'));


var option = {
    title:{
        text: 'Queues 实时状态图'
    },
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    legend: {
        data: ['messages','ready','unacked']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis:  {
        type: 'value'
    },
    yAxis: {
        type: 'category',
        data: []
    },
    series: [
        {
            name: 'messages',
            type: 'bar',
            stack: '总量',
            label: {
                normal: {
                    show: true,
                    position: 'insideleft'
                }
            },
            data: []
        },
        {
            name: 'ready',
            type: 'bar',
            stack: '总量',
            label: {
                normal: {
                    show: true,
                    position: 'insideleft'
                }
            },
            data: []
        },
        {
            name: 'unacked',
            type: 'bar',
            stack: '总量',
            label: {
                normal: {
                    show: true,
                    position: 'outsideRight'
                }
            },
            data: []
        },


    ]
};


myChart.setOption(option);
myChart.showLoading();
window.setInterval(get_data, 5000);
function get_data() {
$.ajax({
        type: "post",
        async: true,
        url: "{% url 'test1:rabbitmq_queue_monitor' %}",
        data:{},
        dataType: "json",
        success: function (data) {
            if(data){
{#                d = data["tasks_num"];#}
{#                for(var i=0; i<d.length; i++){#}
{#                    names.push(d[i].name);#}
{#                }#}
{#                for(var i=0; i<d.length; i++){#}
{#                    nums.push(d[i].total_run_count);#}
{#                }#}
                myChart.hideLoading();
                myChart.setOption({
                    yAxis:{data:data["queues"]},
                    series:[{data:data["messages"]},{data:data["ready"]},{data:data["unacked"]}]
                });
            }
        },
        error:function (errorMsg) {
{#            alert("请求失败");#}
            myChart.hideLoading();
        }
    });
    }

        })
    </script>


{% endblock %}

test1/templates/test1/login.html
<!DOCTYPE HTML>
<html>
<head>
<title>登录</title>
<link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- -->
<script>var __links = document.querySelectorAll('a');function __linkClick(e) { parent.window.postMessage(this.href, '*');} ;for (var i = 0, l = __links.length; i < l; i++) {if ( __links[i].getAttribute('data-t') == '_blank' ) { __links[i].addEventListener('click', __linkClick, false);}}</script>
<script src="/static/js/jquery-3.3.1.min.js"></script>
<script>$(document).ready(function(c) {
	$('.alert-close').on('click', function(c){
		$('.message').fadeOut('slow', function(c){
	  		$('.message').remove();
		});
	});
});
</script>
</head>
<body>
<!-- contact-form -->
<div class="message warning">
<div class="inset">
	<div class="login-head">
		<h1>系统登录</h1>
		 <div class="alert-close"> </div>
	</div>
		<form>
			<li>
				<input id="username" type="text" class="text" value="用户名" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '用户名';}"><a href="#" class=" icon user"></a>
			</li>
				<div class="clear"> </div>
			<li>
				<input id="password" type="password" value="Password" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Password';}"> <a href="#" class="icon lock"></a>
			</li>
			<div class="clear"> </div>
			<div class="submit">
				<input type="submit" onclick="myFunction()" value="登录" id="loginbtn">
{#				<h4><a href="#">Lost your Password ?</a></h4>#}
						  <div class="clear">  </div>
			</div>

		</form>
		</div>
	</div>
	</div>
	<div class="clear"> </div>
<!--- footer --->
<div class="footer">
	<p>Copyright &copy; 2018.</p>
</div>

</body>

<script>
    $(function () {
        $("#loginbtn").click(function () {

        })
    })
</script>

</html>

test1/templates/test1/rabbitmq.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block css %}
<link rel="stylesheet" href="/static/plugins/bootstrap3-editable/css/bootstrap-editable.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/plugins/bootstrap-table/bootstrap-table.min.css">

<link rel="stylesheet" href="/static/plugins/GridManager/css/gm.css">
{% endblock %}

{% block content %}
    <section class="content-header">
    <h1>
        RabbitMQ
        <small>Exchanges & Queues</small>
    </h1>

    <ol class="breadcrumb">
        <li><a href="{% url 'test1:index' %}"><i class="fa fa-dashboard"></i>主页 </a> </li>
        <li class="active">Exchanges & Queues</li>
    </ol>
    </section>
<br>
{#    {% for i in queues %}#}
{#        {{ i }}#}
{#    {% endfor %}#}
{##}
{#    <button id="sync" type="button">sync</button>#}
{#    <label id="l1"></label>#}

    <label>Exchanges</label>
<div class="row">

    <div class="col-xs-12 col-sm-6 col-md-12">
        <table grid-manager="exchanges"></table>
    </div>
</div>
    <br>
    <label>Queues</label>
<div class="row">
<div class="col-xs-12 col-sm-6 col-md-12">
    <table grid-manager="queues"></table>
</div>
</div>
{% endblock %}

{% block script %}
        <script src="/static/js/csrf.js"></script>
    <script src='/static/js/jquery-3.3.1.min.js'></script>
{#<script src="/static/js/jquery-1.10.2.min.js"></script>#}
<script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/plugins/GridManager/js/gm.js"></script>
<script src="/static/plugins/bootstrap3-editable/js/bootstrap-editable.js"></script>
<script src="/static/plugins/bootstrap-table/bootstrap-table.js"></script>
<script src="/static/plugins/bootstrap-table/locale/bootstrap-table-zh-CN.js"></script>
<script src="/static/plugins/bootstrap-table/extensions/editable/bootstrap-table-editable.js"></script>

    <script>

    $(document).ready(function () {
        get_exchanges();
        get_queues();
    });

    function get_exchanges() {
            var table = document.querySelector('table[grid-manager="exchanges"]');
table.GM({
    ajax_data: "{% url 'test1:get_exchanges_table' %}"
    ,ajax_type: 'POST'
    ,query: {pluginId: 1}
    ,supportAjaxPage: true
    ,sizeData: [8,15,20]
    ,pageSize: 8
    ,height: '50%'
    ,columnData: [
        {
            key: 'id',
            text: 'id'
        },{
            key: 'name',
            text: 'Exchange名称'
        }
    ]
})
    }


        function get_queues() {
            var table = document.querySelector('table[grid-manager="queues"]');
table.GM({
    ajax_url: "{% url 'test1:get_queues_table' %}"
    ,ajax_type: 'POST'
    ,query: {pluginId: 1}
    ,supportAjaxPage: true
    ,sizeData: [5,10,15,20]
    ,pageSize: 5
    ,height: '50%'
    ,columnData: [
        {
            key: 'id',
            text: 'id'
        },{
            key: 'name',
            text: ' Queue名称'
        }
    ]
})
    }

    $("#sync").click(function () {
        $.post("{% url 'test1:rabbitmq_sync' %}",function(data){
           $("#l1").html(data["ex_num"],' ',data["qu_num"]);
        });
    });


{#        $('table[grid-manager="test"]').GM({#}
{#        supportRemind: true#}
{#        ,i18n:'zh-cn'#}
{#        ,textConfig:{#}
{#            'page-go': {#}
{#                'zh-cn':'跳转',#}
{#                'en-us':'Go '#}
{#            }#}
{#        }#}
{#        ,disableCache:false#}
{#        ,disableOrder:false#}
{#        ,supportSorting: true#}
{#        ,isCombSorting: true#}
{#        ,sortDownText: 'up'#}
{#        ,sortUpText: 'down'#}
{#        ,supportDrag:true#}
{#        ,supportAjaxPage:true#}
{#        ,ajax_url: "{% url 'test1:get_exchanges' %}"#}
{#        ,ajax_type: 'GET'#}
{#        ,pageSize:30#}
{##}
{#         ,columnData: [{#}
{#                key: 'id',#}
{#                remind: 'id',#}
{#                sorting: 'up',#}
{#                width: '200px',#}
{#                text: 'id'#}
{#            },{#}
{#                key: 'name',#}
{#                remind: 'period',#}
{#                width: '200px',#}
{#                text: 'Exchange 名称'#}
{#            },#}
{#        ]#}
{#    });#}


    </script>

{% endblock %}

test1/templates/test1/result.html
{% extends 'base.html' %}

{% block title %}result{% endblock %}

{% block content %}

<table border="1">
<thead>
<tr>
<td>id</td>
<td>Task_id</td>
<td> 第一个加数</td>
<td>第二个加数</td>
<td>任务状态</td>
<td>结果</td>
<td>开始时间</td>
<td>完成时间</td>
</tr>
</thead>

<tbody>
{% for res in result %}
    <tr>
    <td>{{ res.id }}</td>
    <td>{{ res.task_id }}</td>
    <td>{{ res.first}}</td>
    <td>{{ res.second }}</td>
    <td>{{ res.status }}</td>
    <td>{{ res.result }}</td>
    <td>{{ res.log_date }}</td>
    <td>{{ res.date_done }}</td>
    </tr>
{% endfor %}
</tbody>

</table>

{% endblock %}